import click
from rich.console import Console
from .core import generate_project
from .presets import PresetsManager

console = Console()
presets_manager = PresetsManager()

@click.group()
def main():
    """ML Project Scaffolder - Production Ready"""
    pass

@main.command()
@click.option('--name', prompt='Project Name', help='Name of the project')
@click.option('--preset', default='default', help='Configuration preset to use')
@click.option('--poetry/--no-poetry', default=True, help='Use Poetry for dependency management')
@click.option('--git/--no-git', default=True, help='Initialize Git repository')
@click.option('--dvc/--no-dvc', default=False, help='Initialize DVC')
def init(name, preset, poetry, git, dvc):
    """Initialize a new ML project."""
    try:
        config = presets_manager.load(preset)
    except FileNotFoundError:
        console.print(f"[red]Preset '{preset}' not found. Using default.[/red]")
        config = presets_manager.load('default')

    # Override config with CLI flags
    config['name'] = name
    
    # Manage integrations list
    integrations = config.get('integrations', [])
    if poetry and 'poetry' not in integrations:
        integrations.append('poetry')
    if not poetry and 'poetry' in integrations:
        integrations.remove('poetry')
        
    if git and 'git' not in integrations:
        integrations.append('git')
    if not git and 'git' in integrations:
        integrations.remove('git')

    if dvc and 'dvc' not in integrations:
        integrations.append('dvc')
    
    config['integrations'] = integrations

    generate_project(config)

@main.group()
def presets():
    """Manage configuration presets."""
    pass

@presets.command(name='list')
def list_presets():
    """List available presets."""
    presets = presets_manager.list()
    console.print("[bold]Available presets:[/bold]")
    for p in presets:
        console.print(f"- {p}")

@presets.command(name='save')
@click.argument('name')
def save_preset(name):
    """Save current project configuration as a preset."""
    import os
    from pathlib import Path
    from ruamel.yaml import YAML
    
    yaml = YAML()
    config_path = Path.cwd() / ".mlinit-config.yaml"
    
    if not config_path.exists():
        console.print("[red]No .mlinit-config.yaml found in current directory.[/red]")
        console.print("Are you in the root of a project generated by mlinit?")
        return

    try:
        with open(config_path, "r") as f:
            config = yaml.load(f)
            
        # Clean up instance-specific fields
        if 'name' in config:
            del config['name']
            
        presets_manager.save(name, config)
        console.print(f"[green]Preset '{name}' saved successfully![/green]")
    except Exception as e:
        console.print(f"[red]Failed to save preset: {e}[/red]")

if __name__ == "__main__":
    main()
